server:
  port: 7000
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: ${SSL_ENABLE}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/myrealm
          jwk-set-uri: http://localhost:8085/realms/myrealm/protocol/openid-connect/certs
  reactor:
    debug-agent:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  rsocket:
    server:
      transport: websocket
      mapping-path: https://master-of-prediction.shop:7000/rsocket
      ssl:
        key-store: classpath:keystore.p12
        key-store-password: 1234
        enabled: true
        key-alias: tomcat
        key-store-type: PKCS12

  r2dbc:
    url: r2dbc:mysql://localhost:9876/forecasthub
    username: root
    password: 1234

  main:
    allow-bean-definition-overriding: true
jwt:
  expiration_time: 86400000 #1일
  secret: ${JWT_SECRET}

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
      rsocket: DEBUG
    org.springframework.security: DEBUG
    org.springframework.messaging.rsocket: DEBUG
    org.springframework.security.rsocket: DEBUG  # RSocket Security 전용 디버깅
    io.rsocket: DEBUG
#      r2dbc: TRACE
    org.springframework.data.redis: DEBUG  # Spring Data Redis 로깅 레벨
    io.lettuce.core: DEBUG                 # Redis 클라이언트 Lettuce의 로깅 레벨
    org.springframework.web: DEBUG         # 웹 요청 관련 디버그 (선택 사항)
    root: INFO