server:
  port: 7000
  ssl:
    key-store:  ${KEY_STORE_PATH}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: ${SSL_ENABLE}
spring:
  reactor:
    debug-agent:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  rsocket:
    server:
      transport: websocket
      mapping-path: ${RSOCKET_MAPPING}
      ssl:
        key-store: ${KEY_STORE_PATH}
        key-store-password: ${SSL_KEY_STORE_PASSWORD}
        enabled: true
        key-alias: tomcat
        key-store-type: PKCS12

  r2dbc:
    url: ${DB_USER_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  main:
    allow-bean-definition-overriding: true
jwt:
  expiration_time: 86400000 #1일
  secret: ${JWT_SECRET}

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
#      rsocket: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.messaging.rsocket: DEBUG
#    org.springframework.security.rsocket: DEBUG  # RSocket Security 전용 디버깅
#    io.rsocket: DEBUG
      r2dbc: TRACE
#    org.springframework.data.redis: DEBUG  # Spring Data Redis 로깅 레벨
#    io.lettuce.core: DEBUG                 # Redis 클라이언트 Lettuce의 로깅 레벨
#    org.springframework.web: DEBUG         # 웹 요청 관련 디버그 (선택 사항)
#    root: INFO