spring:
  data:
    mongodb:
      uri: mongodb://ohgiraffers:ohgiraffers@localhost:10001/forecasthub
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI에 접근할 수 있는 경로 설정
  api-docs:
    path: /v3/api-docs      # OpenAPI 문서에 접근할 수 있는 경로 설정
