name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag dudnjsckrgo/chat:$(date +%s)
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Set IMAGE_TAG
      id: tag
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY:  meta_user_24
        IMAGE_TAG:   ${{ env.IMAGE_TAG }}
      run: |
        docker buildx build --platform=linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.30.6/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
    # 타겟 리포지토리 클론
    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        repository: mtvs-3rd-outsider/k8s-config  # 타겟 리포지토리 소유자/이름으로 변경
        path: k8s-config
        token: ${{ secrets.TARGET_REPO_TOKEN }}  # 타겟 리포지토리에 접근할 수 있는 토큰

    # values.yaml 업데이트
    - name: Update values.yaml with new image tag
      run: |
        cd k8s-config
        # yq를 사용하여 app.tag 업데이트
        yq eval '.chat.tag = env(IMAGE_TAG)' -i values.yaml
        # Git 설정
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # 변경 사항 스테이지 및 커밋
        git add values.yaml
        git commit -m "chore: update chat.tag to ${{ env.IMAGE_TAG }}"
    # 변경 사항 푸시
    - name: Push changes to Target Repository
      run: |
        cd k8s-config
        git push origin main  # 타겟 브랜치가 main이 아닌 경우 변경
